apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: selectchatgpt-ingress
  namespace: selectchatgpt
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  tls:
    - hosts:
        - selectchatgpt.jiun.dev
        - api.selectchatgpt.jiun.dev
      secretName: selectchatgpt-tls-secret
  rules:
    - host: selectchatgpt.jiun.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 3000
    - host: api.selectchatgpt.jiun.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: server
                port:
                  number: 3001
