apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selectchatgpt-tls
  namespace: selectchatgpt
spec:
  secretName: selectchatgpt-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - selectchatgpt.jiun.dev
    - api.selectchatgpt.jiun.dev
