apiVersion: v1
kind: Service
metadata:
  name: server-metrics
  namespace: selectchatgpt
  labels:
    app: server
spec:
  type: NodePort
  selector:
    app: server
  ports:
    - port: 3001
      targetPort: 3001
      nodePort: 30301
      name: metrics
